import React from 'react';
import Head from 'next/head';
import TextField from '@material-ui/core/TextField';
import FavoriteIcon from '@material-ui/icons/Favorite';
import InputAdornment from '@material-ui/core/InputAdornment';
import SearchIcon from '@material-ui/icons/Search';
import { useRouter } from 'next/router';
import useStyles from './styles';
import Categories from './components/categories';

const HomePage = (props) => {
    const styles = useStyles();
    const router = useRouter();

    return (
        <div className={styles.homePage}>
            <Head>
                <title>HomePage</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <FavoriteIcon className={styles.favoriteIcon}/>
                <TextField
                    className={styles.searchTextField}
                    id="search-input"
                    variant="outlined"
                    size="small"
                    InputProps={{
                        startAdornment: <InputAdornment position="start">
                            <SearchIcon />
                        </InputAdornment>,
                    }}
                    onClick={() => router.push('/search')}
                />
            </div>
            <Categories />
        </div>
    )
}

export default HomePage;